production:
  solr:
    hostname: 54.244.123.247
    port: 9000
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
  disabled: true


test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
  disabled: true